// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAd1KjLYpqrG7cUD5rM3LGK4--TKNM5Y',
    appId: '1:949517781565:web:5d103c6887cb3f1354b854',
    messagingSenderId: '949517781565',
    projectId: 'tago-a8067',
    authDomain: 'tago-a8067.firebaseapp.com',
    storageBucket: 'tago-a8067.firebasestorage.app',
    measurementId: 'G-PW1M0C2X8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GoJwJF1KXsAd_6gEJwRb2jcteuTw4Vo',
    appId: '1:949517781565:android:f71454778059a49e54b854',
    messagingSenderId: '949517781565',
    projectId: 'tago-a8067',
    storageBucket: 'tago-a8067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNH8Q05gG_9UBMi-Gk7RXPqneacLRDXc',
    appId: '1:949517781565:ios:c9a8ba74a9a44a1354b854',
    messagingSenderId: '949517781565',
    projectId: 'tago-a8067',
    storageBucket: 'tago-a8067.firebasestorage.app',
    iosClientId: '949517781565-n6fa81eu8v2oqpekjr4247hp0dofvlc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagoDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNNH8Q05gG_9UBMi-Gk7RXPqneacLRDXc',
    appId: '1:949517781565:ios:c9a8ba74a9a44a1354b854',
    messagingSenderId: '949517781565',
    projectId: 'tago-a8067',
    storageBucket: 'tago-a8067.firebasestorage.app',
    iosClientId: '949517781565-n6fa81eu8v2oqpekjr4247hp0dofvlc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagoDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRAd1KjLYpqrG7cUD5rM3LGK4--TKNM5Y',
    appId: '1:949517781565:web:fdc2ea000beb732a54b854',
    messagingSenderId: '949517781565',
    projectId: 'tago-a8067',
    authDomain: 'tago-a8067.firebaseapp.com',
    storageBucket: 'tago-a8067.firebasestorage.app',
    measurementId: 'G-Y46MBNBXJ9',
  );
}
